version: '3'

networks:
  backend:
    driver: bridge

volumes:
  mysql:

services:
### Wordpress ############################################
    wordpress:
      build:
        context: wordpress
      ports:
        - "80:80"
        - "443:443"
      restart: always
      environment:
        WORDPRESS_DB_HOST: mysql:3306
        WORDPRESS_DB_USER: default
        WORDPRESS_DB_PASSWORD: secret
        WORDPRESS_DB_NAME: default
        WORDPRESS_TABLE_PREFIX: wp_
        WORDPRESS_DEBUG: "true"
        WORDPRESS_CONFIG_EXTRA: |
          /* CUSTOM CONFIGS */
          define('ALLOW_UNFILTERED_UPLOADS', true);
          define('WP_DEBUG_LOG', true);
      volumes:
        - ./wordpress/php.ini:/usr/local/etc/php/conf.d/uploads.ini
      command: /bin/sh -c "chown www-data:www-data wp-content -R && docker-entrypoint.sh apache2-foreground"
      networks:
        - backend

### MySQL ################################################
    mysql:
      build:
        context: ./mysql
        args:
          - MYSQL_VERSION=5.7
      environment:
        - MYSQL_DATABASE=default
        - MYSQL_USER=default
        - MYSQL_PASSWORD=secret
        - MYSQL_ROOT_PASSWORD=root
        - TZ=America/Sao_Paulo
      volumes:
        - mysql:/var/lib/mysql
        - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      ports:
        - "3306:3306"
      networks:
        - backend
